services:
  db:
    image: mariadb:11
    container_name: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - app-network
  phpmyadmin:
    build: ./phpmyadmin
    depends_on:
      - db
    container_name: phpmyadmin
    restart: unless-stopped
    networks:
      - app-network
    env_file: .env
    volumes:
      - pma:/var/www/pma/html/
    environment:
      PMA_HOSTS: db
      UPLOAD_LIMIT: 50M
  php:
    build: ./php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/joblinkup/
      - ./php/php-dev.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - app-network
    extra_hosts:
      host.docker.internal: host-gateway
  webserver:
    image: caddy:alpine
    depends_on:
      - phpmyadmin
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - pma:/var/www/pma/html/
      - ./src:/var/www/joblinkup/
      - ./caddy-conf:/etc/caddy/
      - ./caddy-data/config:/config
      - ./caddy-data/data:/data 
    networks:
      - app-network

volumes:
  dbdata:
  pma:


networks:
  app-network:
    driver: bridge
