version: '3'

services:
  db:
    image: mariadb:11
    container_name: db
    restart: unless-stopped
    env_file: .env
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
  phpmyadmin:
    build: ./phpmyadmin
    depends_on:
      - db
    container_name: phpmyadmin
    restart: unless-stopped
    networks:
      - app-network
    env_file: .env
    volumes:
      - pma:/var/www/pma/html/
    environment:
      PMA_HOSTS: db
      UPLOAD_LIMIT: 50M
  php:
    image: php:8-fpm
    container_name: php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/joblinkup/
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    depends_on:
      - phpmyadmin
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - pma:/var/www/pma/html/
      - ./src:/var/www/joblinkup/
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network
  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email iamtrazy@proton.me --agree-tos --no-eff-email --staging -d wordpress.local -d www.wordpress.local
volumes:
  dbdata:
  pma:

networks:
  app-network:
    driver: bridge
